GESTURE_ILY = "ILY_SIGN"
GESTURE_ONE_FINGER = "ONE_FINGER"
GESTURE_TWO_FINGERS = "TWO_FINGERS"
GESTURE_OPEN_PALM = "OPEN_PALM"
GESTURE_STOP = GESTURE_OPEN_PALM

ACTIVITY_BY_GESTURE = {
    GESTURE_ILY: "studying",
    GESTURE_ONE_FINGER: "youtube",
    GESTURE_TWO_FINGERS: "lol",
}

ACTIVITIES = ("studying", "youtube", "lol")
